-- SettleUp schema (PostgreSQL)
--
-- Money is stored as BIGINT paise, never NUMERIC or DOUBLE. Integers make the sum-to-zero
-- invariant exact and remove any question of rounding behaviour inside the database.

CREATE TABLE IF NOT EXISTS app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS expense_group (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    currency   VARCHAR(3) NOT NULL DEFAULT 'INR',
    created_by BIGINT NOT NULL,
    -- Bumped by every balance-changing write. Drives both cache invalidation and stale-plan
    -- detection, which is why it lives on the group rather than being derived.
    version    BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_group_creator FOREIGN KEY (created_by) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS group_member (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id  BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_group_member UNIQUE (group_id, user_id),
    CONSTRAINT fk_member_group FOREIGN KEY (group_id) REFERENCES expense_group (id),
    CONSTRAINT fk_member_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS recurring_expense_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT NOT NULL,
    description     VARCHAR(200) NOT NULL,
    total_paise     BIGINT NOT NULL,
    paid_by_user_id BIGINT NOT NULL,
    split_type      VARCHAR(20) NOT NULL,
    day_of_month    INTEGER NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_template_amount CHECK (total_paise > 0),
    CONSTRAINT chk_template_day CHECK (day_of_month BETWEEN 1 AND 31),
    CONSTRAINT fk_template_group FOREIGN KEY (group_id) REFERENCES expense_group (id),
    CONSTRAINT fk_template_payer FOREIGN KEY (paid_by_user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS expense (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id              BIGINT NOT NULL,
    description           VARCHAR(200) NOT NULL,
    total_paise           BIGINT NOT NULL,
    paid_by_user_id       BIGINT NOT NULL,
    split_type            VARCHAR(20) NOT NULL,
    created_by            BIGINT NOT NULL,
    -- Unique when present. This, not Redis, is what actually makes retries safe.
    idempotency_key       VARCHAR(100),
    recurring_template_id BIGINT,
    period_key            VARCHAR(20),
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_expense_amount CHECK (total_paise > 0),
    CONSTRAINT uk_expense_idempotency UNIQUE (idempotency_key),
    -- Stops a job re-run, a restart or a second app instance from charging rent twice.
    CONSTRAINT uk_expense_recurring_period UNIQUE (recurring_template_id, period_key),
    CONSTRAINT fk_expense_group FOREIGN KEY (group_id) REFERENCES expense_group (id),
    CONSTRAINT fk_expense_payer FOREIGN KEY (paid_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_expense_template FOREIGN KEY (recurring_template_id) REFERENCES recurring_expense_template (id)
);

CREATE TABLE IF NOT EXISTS expense_split (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id  BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    share_paise BIGINT NOT NULL,
    CONSTRAINT uk_expense_split UNIQUE (expense_id, user_id),
    CONSTRAINT fk_split_expense FOREIGN KEY (expense_id) REFERENCES expense (id),
    CONSTRAINT fk_split_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS settlement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT NOT NULL,
    from_user_id    BIGINT NOT NULL,
    to_user_id      BIGINT NOT NULL,
    amount_paise    BIGINT NOT NULL,
    idempotency_key VARCHAR(100),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_settlement_amount CHECK (amount_paise > 0),
    CONSTRAINT chk_settlement_parties CHECK (from_user_id <> to_user_id),
    CONSTRAINT uk_settlement_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_settlement_group FOREIGN KEY (group_id) REFERENCES expense_group (id),
    CONSTRAINT fk_settlement_from FOREIGN KEY (from_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_settlement_to FOREIGN KEY (to_user_id) REFERENCES app_user (id)
);

-- The ledger. Append-only by convention: the application only ever INSERTs here, and a user's
-- balance is SUM(delta_paise). There is deliberately no UPDATE path, so nothing can be clobbered
-- by a concurrent writer and every paisa stays traceable to its source.
CREATE TABLE IF NOT EXISTS balance_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    -- Signed. Positive = the group owes this user. Entries written together always sum to zero.
    delta_paise BIGINT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    source_id   BIGINT NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_entry_group FOREIGN KEY (group_id) REFERENCES expense_group (id),
    CONSTRAINT fk_entry_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

-- Balances are read far more often than they are written, and always filtered by group.
CREATE INDEX IF NOT EXISTS idx_balance_entry_group ON balance_entry (group_id);
CREATE INDEX IF NOT EXISTS idx_balance_entry_group_user ON balance_entry (group_id, user_id);
CREATE INDEX IF NOT EXISTS idx_expense_group ON expense (group_id);
CREATE INDEX IF NOT EXISTS idx_expense_split_expense ON expense_split (expense_id);
CREATE INDEX IF NOT EXISTS idx_settlement_group ON settlement (group_id);
CREATE INDEX IF NOT EXISTS idx_group_member_user ON group_member (user_id);
