package com.settleup.expense;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

@Entity
@Table(name = "expense")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Expense {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "group_id", nullable = false)
    private Long groupId;

    @Column(name = "description", nullable = false, length = 200)
    private String description;

    @Column(name = "total_paise", nullable = false)
    private long totalPaise;

    @Column(name = "paid_by_user_id", nullable = false)
    private Long paidByUserId;

    @Enumerated(EnumType.STRING)
    @Column(name = "split_type", nullable = false, length = 20)
    private SplitType splitType;

    @Column(name = "created_by", nullable = false)
    private Long createdBy;

    /**
     * Client-supplied key that makes expense creation safe to retry. Backed by a unique index, so
     * even if two identical requests race past the Redis fast path the database still admits one.
     */
    @Column(name = "idempotency_key", length = 100)
    private String idempotencyKey;

    /** Set when this expense was generated by the recurring-expense job rather than by a human. */
    @Column(name = "recurring_template_id")
    private Long recurringTemplateId;

    /**
     * Identifies the period a generated expense belongs to, e.g. {@code 2026-09}. Unique together
     * with the template id, which is what stops a job re-run from charging rent twice.
     */
    @Column(name = "period_key", length = 20)
    private String periodKey;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;
}
